#ifndef Tile_H
#define Tile_H

enum TileType
{
	TILE_VOID = 0,
	TILE_FLOOR,
	TILE_WALL,
	TILE_WALL_H,
	TILE_SPAWNER_S,
	TILE_SPAWNER_M,
	TILE_SPAWNER_L,
	TILE_SPAWNER_T
};

#define	TILE_SPAWNER_S TILE_FLOOR 
#define	TILE_SPAWNER_M TILE_FLOOR
#define	TILE_SPAWNER_L TILE_FLOOR
#define	TILE_SPAWNER_T TILE_FLOOR

#endif